# Generated by Django 4.0.4 on 2022-05-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Enter car number', max_length=10, verbose_name='number')),
                ('vin_number', models.CharField(help_text='17 symbols <a href="https://www.autodna.com/vin-number">VIN number</a>', max_length=17, verbose_name='VIN number')),
                ('client', models.CharField(help_text='Enter client name', max_length=250, verbose_name='client')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(help_text='Enter car brand (for example, Toyota)', max_length=100, verbose_name='car brand')),
                ('car_model', models.CharField(help_text='Enter car model (for example, Corolla)', max_length=100, verbose_name='car model')),
                ('year', models.IntegerField(help_text='Enter car production year', null=True, verbose_name='year')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'ordering': ['car_brand', 'car_model', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name', max_length=100)),
                ('price', models.FloatField(help_text='service price', verbose_name='price')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='order data')),
                ('quantity', models.IntegerField(help_text='service quantity', verbose_name='quantity')),
                ('status', models.CharField(blank=True, choices=[('l', 'Laukia'), ('v', 'Vykdoma'), ('i', 'įvykdyta'), ('a', 'atšaukta')], default='a', help_text='Status', max_length=1)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='autoservice_1.car', verbose_name='Car')),
                ('service', models.ManyToManyField(help_text='select service', to='autoservice_1.service')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['car_id', 'data'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autoservice_1.model', verbose_name='Model'),
        ),
    ]
