# Generated by Django 4.0.4 on 2022-05-24 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('l', 'Laukia'), ('v', 'Vykdoma'), ('i', 'įvykdyta'), ('a', 'atšaukta')], default='l', help_text='Status', max_length=1),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='service quantity', verbose_name='quantity')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_lines', to='autoservice_1.order', verbose_name='order')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_lines', to='autoservice_1.service', verbose_name='service')),
            ],
        ),
    ]
