# Generated by Django 4.0.4 on 2022-06-02 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservice_1', '0003_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='client'),
            preserve_default=False,
        ),
    ]
