# Generated by Django 4.0.4 on 2022-06-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice_1', '0006_alter_car_image_alter_order_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='image'),
        ),
    ]
