# Generated by Django 4.0.4 on 2022-06-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice_1', '0007_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='autoservice_1.order', verbose_name='order'),
        ),
    ]
